# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.cache/wt [current_project]
set_property parent.project_path C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Detection_FIN.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Compteur.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Commande_Compteur.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/TEMPO_50us.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/GEST_gen.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/GEN_BitSignal.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/FDE.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CMPT_1toNmax.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CMPT3.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CMPT2.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CMPT1.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Attente_1_front.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/LEDS.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/GEN_NPSIGNAL.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CMPT4.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/DFM.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/attente.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/FDE2.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/CLK_50Hz.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Alarme.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/NEOPIXEL.vhd
  C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/sources_1/new/Cerberus.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/constrs_1/new/Cerbere.xdc
set_property used_in_implementation false [get_files C:/Users/dylan_000/Desktop/ENSEA/Projet/Alarme/Alarme.srcs/constrs_1/new/Cerbere.xdc]


synth_design -top Cerberus -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Cerberus.dcp

catch { report_utilization -file Cerberus_utilization_synth.rpt -pb Cerberus_utilization_synth.pb }
